basePath: /api/v1
definitions:
  model.APIResponse:
    properties:
      code:
        description: code
        type: integer
      message:
        description: message
        type: string
    type: object
  model.GetLogsCountResponse:
    properties:
      count:
        type: integer
    type: object
  model.Log:
    properties:
      application:
        description: name of application
        example: app1
        type: string
      hostname:
        description: Hostame
        example: hostname
        type: string
      id:
        description: unique id (in DB)
        type: integer
      meaasge:
        description: log message
        type: string
      messageid:
        description: Message ID
        type: integer
      pid:
        description: process id
        type: string
      pri:
        description: priority (facility*8 + severity)
        type: integer
      timestamp:
        description: timestamp of logline (RFC3339)
        format: date-time
        type: string
      version:
        description: logline version
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: akosbalogh005@gmail.com
    name: Akos Balogh
  description: A sample application for store loglines to immudb
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Immudb Logstore
  version: "1.0"
paths:
  /logs:
    get:
      consumes:
      - application/json
      description: Get stored logs
      parameters:
      - description: Max number of returned logs. Ordered by id desc.
        in: query
        name: count
        type: integer
      - description: Filter for application
        in: query
        name: application
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Log'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.APIResponse'
      security:
      - BasicAuth: []
      summary: Get stored logs
      tags:
      - logs
    post:
      consumes:
      - application/json
      description: Add log(s) to the immudb
      parameters:
      - description: Logs to be storeds
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/model.Log'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.APIResponse'
      security:
      - BasicAuth: []
      summary: Add log(s) to the immudb
      tags:
      - logs
  /logs/count:
    get:
      consumes:
      - application/json
      description: Get number of stored logs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetLogsCountResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.APIResponse'
      security:
      - BasicAuth: []
      summary: Get number of stored logs
      tags:
      - logs
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
